PORT: 9000
PREFIX: api

# token过期时间为7天
tokenExpire: 7

# 数据库配置
datasource:
  driverName: mysql
  host: localhost
  port: 3306
  database: nestjs-mysql-api
  username: root
  password: 123456
  charset: utf8mb4
  loc: Asia/Shanghai
  logging: true

# 腾讯地图api
lbsKey: LW7BZ-NB7C5-QNDSX-VCZVT-D7FQ4

# 阿里oss存储
aliyunOss:
  accessKeyId: 'LTAI4FmwbKtoErzJdwfJmcmd'
  accessKeySecret: 'bu5UZXAG2dXQ6G75bzTDXoTN1VcALv'
  endpointUrl: 'oss-cn-shenzhen'
  bucketUrl: 'https://an-jia-shop.oss-cn-shenzhen.aliyuncs.com'
  bucketName: 'an-jia-shop'
  imgDefaultSize: 5
  supportImgTypes: ['.png', '.jpg', '.gif', '.jpeg']
